"""job dedup fields

Revision ID: f9b7d0059a98
Revises: 6924ae3ed15b
Create Date: 2026-02-20 13:52:23.120794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b7d0059a98'
down_revision: Union[str, Sequence[str], None] = '6924ae3ed15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('canonical_url', sa.String(length=800), nullable=False))
    op.add_column('jobs', sa.Column('external_id', sa.String(length=200), nullable=True))
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.add_column('jobs', sa.Column('first_seen_at', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(), nullable=False))
    op.create_index('ix_jobs_external_id', 'jobs', ['external_id'], unique=False)
    op.create_index('ix_jobs_fingerprint', 'jobs', ['fingerprint'], unique=False)
    op.create_unique_constraint(None, 'jobs', ['canonical_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_index('ix_jobs_fingerprint', table_name='jobs')
    op.drop_index('ix_jobs_external_id', table_name='jobs')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'first_seen_at')
    op.drop_column('jobs', 'fingerprint')
    op.drop_column('jobs', 'external_id')
    op.drop_column('jobs', 'canonical_url')
    # ### end Alembic commands ###
